# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Prima-Image-Magick
version:      0.01
version_from: lib/Prima/Image/Magick.pm
installdirs:  site
requires:
    Image::Magick:                 1
    Prima:                         1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
